<?php

include_once('ec_taxonomy.features.inc');


/**
 * Implementation of hook_menu().
 */
function ec_taxonomy_menu() {
  $items = array();

    /*
    $items['admin/content/categories/edit/%'] = array(
       'title' => 'Edit Category',
	   'description' => '',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('ec_taxonomy_edit_category',3),
       'access callback' => 'user_access',
       'access arguments' => array('administer taxonomy'),
       'type' => MENU_CALLBACK,
       'weight' => 1
    );
	*/

  return $items;
}
/*
function ec_taxonomy_edit_category_submit($form, &$form_state) {

	$tid = $form_state['values']['termid'];
	$name = $form_state['values']['term'];
	$success = db_query("UPDATE {term_data} SET name = '%s' WHERE tid = %d", $name, $tid);
	if($success){
	drupal_set_message(t('The category has been saved.'));
	}else{
	drupal_set_message(t('There was an error saving the category.'),'error');
	}
	//drupal_goto('administer/categories');
}

function ec_taxonomy_edit_category(&$form_state,$tid) {

	$term = taxonomy_get_term($tid);
	//$term = db_result(db_query('SELECT * FROM {term_data} WHERE tid = %d', $tid));

	// get variables
	//global $conf;
	//foreach ($conf['node_options_page'] as $k => $v) {
		//drupal_set_message('>'.$tid.' : '.var_export($term));
	//}
	
	// build form
	$form['termid'] = array(
		'#type' => 'value',
		'#value' => $tid,
	);
	$form['term'] = array(
		'#type' => 'textfield',
		'#title' => t('Category name'),
		'#default_value' => $term->name,
		'#maxlength' => 50,
		'#required' => TRUE,
	);

	$form['submit'] = array('#type' => 'submit', '#value' => t('Save'));

	return $form;
}
*/
