<?php

include_once('ec_admin_access.features.inc');

/**
 * Implementation of hook_help().
*/
function ec_admin_access_help($path, $arg) {
  $output = '';
  
  $path1 = implode("/", arg());
  if($path1 == 'user/1/edit'){
    global $user;
    if($user->uid != 1){
      drupal_set_message('Access Denied','warning');
      drupal_goto('user/1');
      //drupal_set_message('Access Denied','warning');
    }
  }


  return $output;
}

/**
 * Implementation of hook_theme_registry_alter().
 */
/*function ec_admin_access_theme_registry_alter(&$theme_registry) {
  $funcs = &$theme_registry['page']['preprocess functions'];
  $key = array_search('ec_admin_access_preprocess_page', $funcs);
  unset($funcs[$key]);
  array_push($funcs, 'ec_admin_access_preprocess_page');

}*/

/**
 * Preprocess function for the page theme hook.
 *
 */
/*function ec_admin_access_preprocess_page(&$variables) {
  
  global $user;
  if($user->uid > 1){
    $path = implode("/", arg());
    $denied_paths = variable_get('ec_denied_admin_paths',array());
	//drupal_set_message('1::'.$path.' : '.in_array($path,$denied_paths));
    if(in_array($path,$denied_paths)){
      //drupal_access_denied();
      drupal_set_message('access denied');
      drupal_goto('<front>');
    }
  }
}*/

function ec_admin_access_menu_alter(&$items) {

  
    $denied_paths = variable_get('ec_denied_admin_paths',array());
	//drupal_set_message(':::'.$item['link_path'].' : '.in_array($item['link_path'],$denied_paths));
    foreach($denied_paths as $path) {

      if($path == 'user/1/edit'){

      }else{
        $items[$path]['access callback'] = 'ec_admin_access_admin_access';
      }

    }
  
}
function ec_admin_access_admin_access() {
	global $user;
	return ($user->uid == 1) ? TRUE:FALSE;
}
/**
* Implementation of hook_menu_link_alter()
*/
/*function ec_admin_access_menu_link_alter(&$item, $menu) {
  global $user;
  //if($user->uid > 1){
    $denied_paths = variable_get('ec_denied_admin_paths',array());
	//drupal_set_message(':::'.$item['link_path'].' : '.in_array($item['link_path'],$denied_paths));
    if (in_array($item['link_path'],$denied_paths)) {
      $item['hidden'] = 1;
    }
  //}
}*/

