<?php

include_once('ec_theme_acquia_prosper.features.inc');

function ec_theme_acquia_prosper_form_alter(&$form, $form_state, $form_id) {

  //global $user;
  //global $base_path;
  //$node = $form['#node'];

  switch($form_id){
    case 'system_themes_form':

        $form['acquia_prosper']['info']['#value']['description'] = '';

        //$form['acquia_prosper']['info']['#value']['version'] = '';

        unset($form['fusion_starter']);
        unset($form['fusion_core']);

        unset($form['status']['#options']['fusion_starter']);
        unset($form['status']['#options']['fusion_core']);
 
        unset($form['theme_default']['#options']['fusion_starter']);
        unset($form['theme_default']['#options']['fusion_core']);


      
      break;
    case 'system_theme_settings':

			
	break;
  }

}
