<?php

/**
 * Implementation of hook_strongarm().
 */
function ec_signup_strongarm() {
  $export = array();
  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'signup_date_field_event';
  $strongarm->value = 'field_date';

  $export['signup_date_field_event'] = $strongarm;
  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'signup_node_default_state_event';
  $strongarm->value = 'allowed_off';

  $export['signup_node_default_state_event'] = $strongarm;
  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'signup_status_invite_status';
  $strongarm->value = '1';

  $export['signup_status_invite_status'] = $strongarm;
  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'signup_status_notifications_delete';
  $strongarm->value = 1;

  $export['signup_status_notifications_delete'] = $strongarm;
  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'signup_status_notifications_statuses';
  $strongarm->value = array(
    2 => 2,
  );

  $export['signup_status_notifications_statuses'] = $strongarm;
  return $export;
}
